Add CI and testing suite
shimming-toolbox/shimming-toolbox-matlab pull request #67
Opened 2020-05-08 15:06 UTC by jcohenadad

The purpose of this PR is to establish a continuous integration (CI) framework using Github actions and a test suite with [MOxUnit](https://github.com/MOxUnit/MOxUnit).

2020-05-08 19:24 UTC, kousu commented
Wow https://github.com/joergbrech/moxunit-action/ is great! Unfortunately there's a lot of compatibility problems with the current code base and Octave that will need to be addressed first before we can run it in CI. You can see that Action uses Octave:


I am very much in support of going in that direction but we probably need to do a separate Octave-compatibility PR for it.

2020-05-08 19:55 UTC, kousu commented
Also I would recommend rebase-squashing all the commits to `.github/workflows/main.yml` together. There's no way to debug CI without uploading to CI, but once it's working there's nothing to be learned from keeping the experimental stage around.

2020-05-08 20:29 UTC, jcohenadad commented
> Also I would recommend rebase-squashing all the commits to .github/workflows/main.yml together. There's no way to debug CI without uploading to CI, but once it's working there's nothing to be learned from keeping the experimental stage around.

i know it's ugly... unfortunately i have some other emergencies to take care off and i won,t have the time to do a proper cleaning

2020-05-18 00:59 UTC, po09i commented
I squashed the commits to the best of my ability in this [branch](https://github.com/shimming-toolbox/shimming-toolbox/tree/ad/ci-github-actions-squashed). If this work, I can apply the changes to this branch.

2020-05-18 03:20 UTC, jcohenadad commented
@po09i could you do the squash directly in my branch and then leave your comments— thanks

2020-05-18 20:46 UTC, po09i commented on .github/workflows/main.yml
> +        test: tests
The argument name should be called "tests" according to [mox-unit-action repo](https://github.com/joergbrech/moxunit-action/tree/f7682ab17e6b552d39059d5d5c68fd2d176e67fc). This should remove the warning that was thrown when running the step: run MoxUnit tests.

2020-05-18 20:48 UTC, po09i requested changes

2020-05-18 20:48 UTC, po09i commented on .github/workflows/main.yml
> +        test: tests
The argument name should be called "tests" according to [mox-unit-action repo](https://github.com/joergbrech/moxunit-action/tree/f7682ab17e6b552d39059d5d5c68fd2d176e67fc). This should remove the warning that was thrown when running the step: run MoxUnit tests.

2020-05-18 20:59 UTC, jcohenadad commented on .github/workflows/main.yml
> +        test: tests
good point! would you mind fixing it directly in the branch? thx

2020-05-18 21:11 UTC, po09i approved these changes

2020-05-18 21:16 UTC, merged