Added logfile for realtime_zshim
shimming-toolbox/shimming-toolbox-matlab pull request #80
Opened 2020-05-19 01:42 UTC by evaalonsoortiz

solves #79

2020-05-19 03:23 UTC, rtopfer requested changes
call needs to be to `sortdicoms` and not `MaRdI.sortdicoms`

2020-05-19 03:23 UTC, rtopfer commented on example/realtime_zshim.m
> -        sortdicoms( unsortedDicomDir, sortedDicomDir, 1 );
@evaalonsoortiz `sortdicoms` is now a [standalone function ](https://github.com/shimming-toolbox/shimming-toolbox/blob/master/misc/sortdicoms.m) on master. (merge current master into the issue branch before testing)

2020-05-19 03:39 UTC, rtopfer commented on Img/FieldEval.m
> -    % scale RIRO by RMSE of physio signal
Does this need to be removed?
Normalizing by the RMSE actually makes Riro.img somewhat interpretable: i.e. if subject A's breathing causes more b0 variation than subject B, one can see that in a side-by-side plot of Riro.img for each subject.
Without rescaling, one can't make the comparison since Riro.img will be affected arbitrarily by the baseline offset in the respiratory trace (i.e. how tightly the belt was fastened)

2020-05-19 14:25 UTC, evaalonsoortiz commented on example/realtime_zshim.m
> -        sortdicoms( unsortedDicomDir, sortedDicomDir, 1 );
done:
https://github.com/shimming-toolbox/shimming-toolbox/blob/eca9b6f9cc4641caaf0d6c0ff83222f74edd02c0/example/realtime_zshim.m#L84

2020-05-19 14:28 UTC, evaalonsoortiz commented on Img/FieldEval.m
> -    % scale RIRO by RMSE of physio signal
I think that scaling is useful, when you're plotting the images (the user can do this him/herself when plotting). However, I think it's logical that the output of a fitting method should return all the constants with the same units. Otherwise, it could be really confusing.

2020-05-19 14:57 UTC, rtopfer commented on Img/FieldEval.m
> -    % scale RIRO by RMSE of physio signal
ah I think it's that the comment in the code is misleading—it's the multiplication by the RMSE that does exactly that^: converts Riro.img to _Hz_. Without the multiplication, Riro.img is in Hz/unit PMU.

I agree though, the handling of all RIRO-related stuff in the code is all overly confusing (e.g. in terms of units, and _where_ the the variable is accessed—buried as it is as Field.Model.Riro.img)...

I'm going to propose we abandon the whole MaRdI class structure (from which FieldEval inherits). If we go that way then the form of all this stuff^ will change (hopefully easier to tidy it up).

2020-05-19 15:09 UTC, evaalonsoortiz commented on Img/FieldEval.m
> -    % scale RIRO by RMSE of physio signal
Right, I made a mistake in my previous comment. If you are requesting a linear fit (a + b*pressure) you expect that the units of b are "something"/[units of pressure]. If modelfield() returns anything else, it's easy to miss that since it is buried in another file.

2020-05-19 15:24 UTC, jcohenadad commented on example/realtime_zshim.m
> +% LAST MODIFIED: May 2020
remove the date-- that's what github is for

2020-05-19 15:27 UTC, rtopfer commented on Img/FieldEval.m
> -    % scale RIRO by RMSE of physio signal
Indeed. There are pros+cons to both outputs.

Anyway, the scaling factor is returned in `Field.Model.Riro.Aux.Data.p`. For now, can you just rescale in _realtime_zshim.m_ and leave `FieldEval.m` as it is? the original scaling is already assumed in other dependent parts of the code, e.g. `ShimOpt.m`, so they would have to be changed as well.

2020-05-19 15:30 UTC, rtopfer commented on example/realtime_zshim.m
> +% LAST MODIFIED: May 2020
we can vote on it but I suggest from now on we do away with the tags as well, i.e.
```
% Ryan Topfer, MSc. ryan.topfer@polymtl.ca
% Eva Alonso Ortiz (EAO), PhD. eva.alonso.ortiz@gmail.com 
```

2020-05-19 15:36 UTC, jcohenadad commented on example/realtime_zshim.m
> +% LAST MODIFIED: May 2020
also a useful feature of github: https://github.com/shimming-toolbox/shimming-toolbox/graphs/contributors

2020-05-19 15:55 UTC, rtopfer commented on example/realtime_zshim.m
> +% LAST MODIFIED: May 2020
precisely. (+commit history already reveals who did what)

2020-05-20 01:04 UTC, evaalonsoortiz commented on Img/FieldEval.m
> -    % scale RIRO by RMSE of physio signal
Done

2020-05-20 01:04 UTC, evaalonsoortiz commented on example/realtime_zshim.m
> +% LAST MODIFIED: May 2020
Done

2020-05-20 14:02 UTC, evaalonsoortiz commented on example/realtime_zshim.m
> +% LAST MODIFIED: May 2020
> remove the date-- that's what github is for

Thinking about this further: Including the names and dates seems to be the habit that people generally have. I know that git does this for you, but it takes more digging and knowhow than simply glancing at the header. When I look at code, if I see a particular snippet that interests me, I find it useful to know right away who wrote it so I can potentially contact them for more info.

2020-05-20 16:56 UTC, jcohenadad commented on example/realtime_zshim.m
> +% LAST MODIFIED: May 2020
Including the date has indeed been a habit when people were not using version control framework, but this habit has now evolved within modern software engineering framework. There are of course many exceptions to this rule, but I see strong arguments against maintaining the date, the strongest being that maintaining a date is prone to error, for example in [this file](https://github.com/shimming-toolbox/shimming-toolbox/blob/master/example/realtime_zshim.m#L54), which indicates "LAST MODIFIED: Jan. 2020" whereas last commit is from [15 days ago](https://github.com/shimming-toolbox/shimming-toolbox/commit/19b6d55b148bf0185738edd6d159806196958da3). There are other examples, and there will be more in the future. I'd rather have no date than a wrong date. 

As for the authors, I feel less strongly about it. However, two things to keep in mind:
- The purpose of an open-source project is that multiple people contribute to the codebase. So, an initial code could indeed be explicitly signed in the file header, however people should be aware that the file is reviewed by the team during PR (and code review *is* an intellectual contribution) and is prone to being modified by others as time goes by (bug fixes, new features, etc.). 
- The purpose of the "Support/Contact" link in the shimming-toolbox website is precisely to redirect users to the team. 
But again, I am not opposed to a 2-tear system, i.e., mention the "initial contribution" (e.g. Created by: XXX) and having a github-based contribution tracking system, which is referenced as a link in the "Contributors" section of the website.

2020-05-22 02:16 UTC, jcohenadad approved these changes
I have not tested the code (only glanced at it)

2020-05-22 02:46 UTC, rtopfer approved these changes

2020-05-22 02:52 UTC, merged